spring:
  profiles:
    active: ${profile.active}
  main:
    banner-mode: off
  servlet:
    multipart:
      # max total file size
      max-request-size: 20MB
      # max single file size
      max-file-size: 5MB
mybatis-plus:
  global-config:
    banner: false
    db-config:
      logic-delete-field: flag
      logic-delete-value: true
      logic-not-delete-value: false
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
---
spring:
  config:
    activate:
      on-profile: prod
  datasource:
    url: ${MYSQL_URL}
    driver-class-name: com.mysql.cj.jdbc.Driver
  data:
    redis:
      url: ${REDIS_URL} # https://console.upstash.com/
server:
  port: 8000
credentials:
  secret-key: ${SECRET_KEY}
  salt: ${SALT}
---
spring:
  config:
    activate:
      on-profile: dev
  datasource:
    url: ${MYSQL_URL}
    driver-class-name: com.mysql.cj.jdbc.Driver
  data:
    redis:
      url: ${REDIS_URL} # https://console.upstash.com/
server:
  port: 8080
credentials:
  secret-key: ${SECRET_KEY}
  salt: ${SALT}
---

