spring:
  profiles:
    active: ${profile.active}
  main:
    banner-mode: off
  servlet:
    multipart:
      # max total file size
      max-request-size: 20MB
      # max single file size
      max-file-size: 5MB
mybatis-plus:
  global-config:
    banner: false
    logic-delete-field: flag
    logic-delete-value: true
    logic-not-delete-value: false
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl

---
spring:
  config:
    activate:
      on-profile: prod
  datasource:
    url: ${MYSQL_URL}
    driver-class-name: com.mysql.cj.jdbc.Driver
  redis:
    # https://console.upstash.com/
    host: ${REDIS_HOST}
    password: ${REDIS_PASSWORD}
    port: ${REDIS_PORT}
server:
  port: 8000
credentials:
  secret-key: u8dh39hd9312
  salt: 89j3@129%
  qiniu:
    url: rhlzi0l5u.bkt.gdipper.com
    bucket: sbblog-images
    accessKey: Kp_Y3bYqBHHqi4FPE56lKz-JI1J1yxBzO0GHpY17
    accessSecretKey: P9KBmg0CwKwiquMI4dSgADNBPO9AC-Jic6K4dzDv

---
spring:
  config:
    activate:
      on-profile: dev
  datasource:
    url: jdbc:mysql://localhost:3306/blog-test
    username: root
    password: password
    driver-class-name: com.mysql.cj.jdbc.Driver
  redis:
    # https://console.upstash.com/
    host: ${REDIS_HOST}
    password: ${REDIS_PASSWORD}
    port: ${REDIS_PORT}
server:
  port: 8080
credentials:
  secret-key: u8dh39hd9312
  salt: 89j3@129%
  qiniu:
    url: rhlzi0l5u.bkt.gdipper.com
    bucket: sbblog-images
    accessKey: Kp_Y3bYqBHHqi4FPE56lKz-JI1J1yxBzO0GHpY17
    accessSecretKey: P9KBmg0CwKwiquMI4dSgADNBPO9AC-Jic6K4dzDv

---

